=== quyang1995/itserver/itserver-web/src/main/resources/xml/xsd/api.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:annotation>
		<xs:appinfo>api xsd</xs:appinfo>
		<xs:documentation xml:lang="en">
			tss.rajax.me
		</xs:documentation>
	</xs:annotation>


	<xs:attribute name="id" type="xs:string" />
	<xs:attribute name="value" type="xs:string" />
	<xs:attribute name="ref" type="xs:string" />
	<xs:attribute name="except" type="xs:boolean" />

	<xs:attribute name="name" type="xs:string" />
	<xs:attribute name="text" type="xs:string" />
	<xs:attribute name="type" type="xs:string" />
	<xs:attribute name="searchFor" type="xs:string" />
	<xs:attribute name="allowFiles" type="xs:string" />
	<xs:attribute name="binaryName" type="xs:string" />
	<xs:attribute name="minLength" type="xs:string" />
	<xs:attribute name="maxLength" type="xs:string" />
	<xs:attribute name="maxSize" type="xs:int" />
	<xs:attribute name="maxUploadCount" type="xs:int" />
	<xs:attribute name="regex" type="xs:string" />
	<xs:attribute name="required" type="xs:boolean" />
	<xs:attribute name="description" type="xs:string" />
	<xs:attribute name="area" type="xs:string" />

	<xs:attributeGroup name="propertyAttrGroup">
	    <xs:attribute ref="ref" />
	    <xs:attribute ref="name" />
		<xs:attribute ref="type" />
		<xs:attribute ref="searchFor" />
		<xs:attribute ref="allowFiles" />
		<xs:attribute ref="binaryName" />
		<xs:attribute ref="minLength" />
		<xs:attribute ref="maxLength" />
		<xs:attribute ref="maxSize" />
		<xs:attribute ref="maxUploadCount" />
		<xs:attribute ref="regex" />
		<xs:attribute ref="required" />
		<xs:attribute ref="description" />
		<xs:attribute ref="area" />
	</xs:attributeGroup>

	<xs:element name="api">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="version" />
				<xs:element ref="common-property" maxOccurs="unbounded" />
				<xs:element ref="item" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>


    <xs:element name="version">
        <xs:complexType>
            <xs:attribute ref="value" use="required" />
        </xs:complexType>
    </xs:element>
    <xs:element name="common-property">
        <xs:complexType>
            <xs:attribute ref="name" use="required" />
            <xs:attribute ref="type" use="required" />
            <xs:attribute ref="description" use="required" />
            <xs:attribute ref="required"/>
            <xs:attribute ref="regex"/>
            <xs:attribute ref="minLength"/>
            <xs:attribute ref="maxLength"/>
        </xs:complexType>
    </xs:element>
	<xs:element name="item">
		<xs:complexType>
			<xs:sequence>
                <xs:element name="request" maxOccurs="1" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="property" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:attributeGroup ref="propertyAttrGroup"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="response" maxOccurs="1" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="property" maxOccurs="unbounded"  minOccurs="0">
                                <xs:complexType>
                                    <xs:attribute ref="name"/>
                                    <xs:attribute ref="except"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
			</xs:sequence>
			<xs:attribute ref="id" use="required" />
			<xs:attribute ref="description" use="required" />
		</xs:complexType>
	</xs:element>


</xs:schema>

=== quyang1995/itserver/itserver-web/src/main/resources/xml/api.xml
<?xml version="1.0" encoding="UTF-8"?>
<api xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="xsd/api.xsd">

    <version value="0.1"/>

    <!--

    以下属性可用于 common-property 和 property 对象;

    name：           [必填][唯一]全局标识, 相同name时后面覆盖前面；
    type：           [必填]类型, 目前支持: string, int, long, double, date[YYYY-MM-DD hh:mm:ss/YYYY-MM-DD]；
    description：    [必填]描述；
    regex：          [非必填]正则表达式；
    maxLength：      [非必填]最大长度；
    minLength：      [非必填]最小长度；
    searchFor：      [非必填]模糊查询字段, 格式: 字段名1@字段名2...；
                            该属性仅可用在 name="searchText" 对象上;
    maxSize：        [非必填]上传附件的最大尺寸；
    maxUploadCount： [非必填]附件上传最大数量；
    allowFiles：     [非必填]允许上传的附件文件类型；
    required：       [非必填]是否必填, 可选值: false|true；
    ref：            [非必填]property独有属性, 用于引用common-property对象；
    -->

    <!--

    ******** common开头的全局属性必须定义在xml文件最顶部 ********

    全局属性
    用于定义各种全局属性,供后面接口中引用
    -->
    <common-property name="code" type="string" required="true" description="返回码"/>
    <common-property name="msg" type="string" required="true" description="返回信息"/>
    <common-property name="pageNum" type="int" required="true" description="页码"/>
    <common-property name="pageSize" type="int" required="true" description="每页显示记录数"/>
    <common-property name="total" type="int" required="true" description="总记录数"/>

    <!--业务层通用字段抽取-->
    <common-property name="mobileNo" type="String" regex="^(13[0-9]|14[0-9]|15[0-9]|16[0-9]|17[0-9]|18[0-9])[0-9]{8}$"
                     maxLength="11" description="手机号"/>
    <common-property name="email" type="String"
                     regex="^[a-zA-Z0-9.!#$%'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$"
                     maxLength="50" description="电子邮箱"/>
    <common-property name="password" type="String" regex="^([a-zA-Z0-9!@#$%^*_]{8,16})$" maxLength="16"
                     description="管理员登录密码"/>

    <common-property name="employeeCode" type="String" description="登录员工code" />
    <common-property name="employeeName" type="String" description="登录员工名" />


    <!-- ——————————————————————————————————————————我是分割线—————————————————————————————————————————— -->

    <!--
    ******** PRODUCT ********
    -->
    <!--
        URL:
        /api/product/list

        说明:获取产品列表信息

    -->
    <item id="api_product_list" description="获取产品列表信息">
        <request>
            <property ref="pageNum"/>
            <property ref="pageSize"/>
            <property name="accountId" type="string" required="true"/>
            <property name="productStatus" type="string" required="true"/>
            <property name="mySelf" type="string" required="true"/>
            <property name="searchText" type="string" required="true"/>
        </request>
    </item>
    <!--
        URL:
        /api/product/nameList

        说明:根据产品名字返回前20条产品信息

    -->
    <item id="api_product_nameList" description="根据产品名字查询产品信息">
        <request>
            <property name="name" type="string" required="true"/>
        </request>
    </item>






    <!--
        ******** PROGRAM ********
        -->
    <!--
        URL:
        /api/program/list

        说明:获取项目列表信息

    -->
    <item id="api_program_list" description="获取项目列表信息">
        <request>
            <property ref="pageNum"/>
            <property ref="pageSize"/>
            <property name="accountId" type="string" required="true"/>
            <property name="programStatus" type="int" required="true"/>
            <property name="isPart" type="int" required="true"/>
            <property name="searchText" type="string" required="true" maxLength="30" description="搜索内容"/>
        </request>
    </item>

    <!--
        URL:
        /api/program/limitList

        说明:模糊搜索返回20条项目列表信息

    -->
    <item id="api_program_limitList" description="模糊搜索返回20条项目列表信息">
        <request>
            <property name="name" type="string" required="true" minLength="2" description="搜索内容"/>
        </request>
    </item>

    <!--
        URL:
        /api/program/get

        说明:通过ID获取项目基本信息

    -->
    <item id="api_program_get" description="通过ID获取项目基本信息">
        <request>
            <property name="id" type="int" required="true"/>
        </request>
    </item>

    <!--
        URL:
        /api/program/add

        说明:新增项目基本信息

    -->
    <item id="api_program_add" description="新增项目基本信息">
        <request>
            <property name="productId" type="int" required="true"/>
            <property name="name" type="string" required="true"/>
            <property name="descp" type="string" required="false"/>
            <property name="commitDate" type="string" required="true"/>
            <property name="startDate" type="string" required="true"/>
            <property name="grayReleaseDate" type="string" required="true"/>
            <property name="releaseDate" type="string" required="true"/>
            <property name="likeProduct" type="string" required="false"/>
            <property name="likeProgram" type="string" required="false"/>
            <property name="type" type="int" required="true"/>
            <property name="programStatus" type="int" required="true"/>
            <property name="programEmployee" type="string" required="false"/>
        </request>
    </item>

</api>
