=== quyang1995/itserver/itserver-web/src/main/resources/xml/xsd/datatables.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:annotation>
        <xs:appinfo>hanna datatables xsd</xs:appinfo>
        <xs:documentation xml:lang="en">
            java-tools.com
        </xs:documentation>
    </xs:annotation>

    <xs:attribute name="id" type="xs:string"/>
    <xs:attribute name="value" type="xs:string"/>
    <xs:attribute name="text" type="xs:string"/>
    <xs:attribute name="defText" type="xs:string"/>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="isURL" type="xs:boolean"/>

    <xs:element name="saber-datatables">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="version" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="globalValue" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="language" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="datatables" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="version">
        <xs:complexType>
            <xs:attribute ref="value" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="globalValue">
        <xs:complexType>
            <xs:attribute ref="name" use="required"/>
            <xs:attribute ref="value" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="language">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="item" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="paginate" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="datatables">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="datatable" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="datatable">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="property" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="id" use="required"/>
            <xs:attribute ref="name" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="property">
        <xs:complexType>
            <xs:attribute ref="name" use="required"/>
            <xs:attribute ref="value" use="required"/>
            <xs:attribute ref="isURL"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="item">
        <xs:complexType>
            <xs:attribute ref="name" use="required"/>
            <xs:attribute ref="text" use="required"/>
            <xs:attribute ref="defText" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="paginate">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="item" minOccurs="0" maxOccurs="4"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== quyang1995/itserver/itserver-web/src/main/resources/xml/datatables.xml
<?xml version="1.0" encoding="UTF-8"?>
<saber-datatables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="xsd/datatables.xsd">

    <version value="1.0"/>

    <globalValue name="totalRecordsKey" value="iTotalRecords"/>
    <globalValue name="totalDisplayRecordsKey" value="iTotalDisplayRecords"/>
    <globalValue name="dataKey" value="aaData"/>

    <language>
        <item name="sInfoFiltered" text="longfor.dt.sInfoFiltered" defText="(搜索自 _MAX_ 条数据)"/>
        <item name="sLengthMenu" text="longfor.dt.sLengthMenu" defText="每页显示 _MENU_ 条数据"/>
        <item name="sZeroRecords" text="longfor.dt.sZeroRecords" defText="没有数据"/>
        <item name="sInfo" text="longfor.dt.sInfo" defText="_START_ 到 _END_ /共 _TOTAL_ "/>
        <item name="sInfoEmpty" text="longfor.dt.sInfoEmpty" defText=" "/>
        <item name="sProcessing" text="" defText="加载中..."/>
        <item name="sSearch" text="longfor.dt.sSearch" defText="搜索"/>
        <paginate>
            <item name="sFirst" text="" defText="首页"/>
            <item name="sPrevious" text="" defText="前一页"/>
            <item name="sNext" text="" defText="后一页"/>
            <item name="sLast" text="" defText="尾页"/>
        </paginate>
    </language>


    <datatables>

        <!--
        未使用
        ******** dafault datatable ********
        -->
        <datatable id="default" name="默认样式的datatable">
            <property name="bLengthChange" value="false"/>
            <property name="bServerSide" value="true"/>
            <property name="sAjaxSource" value="" isURL="true"/>
            <property name="language" value="dt/ajax_dt/lag" isURL="true"/>
            <property name="pagingType" value="bootstrap_full_number"/>
            <property name="pageLength" value="10"/>
            <property name="bStateSave" value="false"/>
        </datatable>
        <!-- ******** dafault datatable end ******** -->


    </datatables>


    <!-- ——————————————————————————————————————————我是分割线—————————————————————————————————————————— -->

</saber-datatables>
